#!/bin/bash

#beakerx install

#jupyter labextension install beakerx-jupyterlab --dev

#jupyter contrib nbextension install --user
#jupyter nbextension enable --py widgetsnbextension
#jupyter nbextension enable python-markdown/main

jupyter labextension install @jupyter-widgets/jupyterlab-manager --dev
jupyter labextension install @jupyterlab/plotly-extension --dev

jupyter lab build
